crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include("customer.urls", namespace="customer")),
    url(r'^orders/$', include("orders.urls", namespace="orders")),
    url(r'^admin/', admin.site.urls),
]

customer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^customers/$', views.CustomerIndex.as_view(), name="view-all-customers"),
    url(r'^customers/details/(?P<id>\d+)/$', views.CustomerView.as_view(), name="customer-view"),
    url(r'^customers/add-new/$', views.AddCustomer.as_view(), name="customer-addnew"),
    url(r'^logout/$', views.Logout, name="logout"),
]

customer/models.py
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models

now = timezone.now()

class Customer(models.Model):
    date_added = models.DateField(default=now)
    cCat = models.CharField(max_length=2, choices=(
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D")
    ))
    title = models.CharField(max_length=10, choices=(
        ("NA", "NA"),
        ("Mr.", "Mr."),
        ("Ms.", "Ms."),
        ("Mrs.", "Mrs."),
        ("S.", "S."),
        ("Dr.", "Dr."),
        ("Prof.", "Prof."),
    ))
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    sex = models.CharField(max_length=15, choices=(
        ("Male", "Male"),
        ("Female", "Female"),
    ))
    rCat = models.CharField(max_length=20, choices=(
        ("NA", "NA"),
        ("H", "H"),
        ("S", "S"),
        ("C", "C"),
        ("M", "M"),
    ), verbose_name="Religion")
    anniversary = models.DateField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    mobile1 = models.BigIntegerField(blank=True, null=True)
    mobile2 = models.BigIntegerField(blank=True, null=True)
    residence_phone = models.BigIntegerField(blank=True, null=True)
    office_phone = models.BigIntegerField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    addline1 = models.CharField(max_length=100, blank=True, null=True, verbose_name="Address Line 1")
    addline2 = models.CharField(max_length=100, blank=True, null=True, verbose_name="Address Line 2")
    city = models.CharField(default="Delhi", max_length=100, blank=True, null=True)
    pincode = models.IntegerField(blank=True, null=True)
    locality = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True, default="India")

    def __str__(self):
        return self.first_name + " " + self.last_name

customer/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import Customer

def Logout(request):
    logout(request)
    return redirect("customer:index")

class IndexView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, "index.html", {"title":"Login to Optics CRM"})
        else:
            return render(request, "login.html", {"title":"Index"})

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return render(request, "index.html", {
                "title":"Index"
                })
            else:
                return render(request, "login.html", {
                "title":"Login"
                })
        else:
            return render(request, "login.html", {
            "title":"Login",
            })

class CustomerView(View):
    def get(self, request, id):
        customer = Customer.objects.get(pk=id)

        return render(request, "customer-view.html", {
        "title":"Viewing Customer",
        "customer":customer,
        })

    def post(self, request, id):
        customer = Customer.objects.get(pk=id)

        customer.title = request.POST.get("title")
        customer.first_name = request.POST.get("fname")
        customer.middle_name = request.POST.get("mname")
        customer.last_name = request.POST.get("lname")
        customer.sex = request.POST.get("sex")
        customer.anniversary = request.POST.get("anndate")
        customer.email = request.POST.get("email")
        customer.comments = request.POST.get("specialRemarks")
        customer.addline2 = request.POST.get("add2")
        customer.addline1 = request.POST.get("add1")
        customer.locality = request.POST.get("locality")
        if request.POST.get("pincode") == "":
            customer.pincode = None
        else:
            customer.pincode = int(request.POST.get("pincode"))
        if request.POST.get("mobile1")=="" or None:
            customer.mobile1 = None
        else:
            customer.mobile1 = int(request.POST.get("mobile1"))
        if request.POST.get("rphone")=="" or None:
            customer.rphone = None
        else:
            customer.rphone = int(request.POST.get("rphone"))
        if request.POST.get("mobile2")=="" or None:
            customer.mobile2 = None
        else:
            customer.mobile2 = int(request.POST.get("mobile2"))
        if request.POST.get("ophone")=="" or None:
            customer.ophone = None
        else:
            customer.ophone = int(request.POST.get("ophone"))
        if request.POST.get("anndate")=="":
            customer.anniversary = None

        else:
            customer.anniversary = datetime.datetime.strptime(request.POST.get("ann-date"), "%d/%m/%Y").strftime("%Y-%m-%d")
        if request.POST.get("bod")=="":
            customer.date_of_birth = None
        else:
            customer.date_of_birth = datetime.datetime.strptime(request.POST.get("bod"), "%d/%m/%Y").strftime("%Y-%m-%d")
        customer.save()

        return render(request, "customer-view.html", {
        "title":"Viewing Customer",
        "customer":customer,
        })


class CustomerIndex(View):
    def get(self, request):
        customers = Customer.objects.all()[:10]
        return render(request, "customer-index.html",{
        "title":"View all customers",
        "customers":customers,
        })

class AddCustomer(View):
    def get(self, request):

        return render(request, "customer-new.html", {
        "title":"Add New Customer",
        })

    def post(self, request):
        title = request.POST.get("title")
        if request.POST.get("fname") == "":
            fname = None
        else:
            fname = request.POST.get("fname")
        if request.POST.get("mname") == "":
            mname = None
        else:
            mname = request.POST.get("mname")
        lname = request.POST.get("lname")
        email = request.POST.get("email")
        sex = request.POST.get("sex")
        if request.POST.get("mobile1")=="" or None:
            mobile1 = None
        else:
            mobile1 = int(request.POST.get("mobile1"))
        if request.POST.get("rphone")=="" or None:
            rphone = None
        else:
            rphone = int(request.POST.get("rphone"))
        if request.POST.get("mobile2")=="" or None:
            mobile2 = None
        else:
            mobile2 = int(request.POST.get("mobile2"))
        if request.POST.get("ophone")=="" or None:
            ophone = None
        else:
            ophone = int(request.POST.get("ophone"))
        if request.POST.get("ann-date")=="":
            anndate = None
        else:
            anndate = datetime.datetime.strptime(request.POST.get("ann-date"), "%d/%m/%Y").strftime("%Y-%m-%d")
            print anndate
        if request.POST.get("bod")=="":
            bod = None
        else:
            bod = datetime.datetime.strptime(request.POST.get("bod"), "%d/%m/%Y").strftime("%Y-%m-%d")
            print bod
        add1 = request.POST.get("add1")
        add2 = request.POST.get("add2")
        locality = request.POST.get("locality")
        if request.POST.get("pincode")=="":
            pincode = None
        else:
            pincode = int(request.POST.get("pincode"))

        customer = Customer.objects.create(title=title, first_name=fname, middle_name=mname, last_name=lname, sex=sex, anniversary=anndate, email=email, mobile1=mobile1, mobile2=mobile2,
        residence_phone=rphone, office_phone=ophone, date_of_birth=bod, addline1=add1, addline2=add2, locality=locality, pincode=pincode)

        return render(request, "customer-view.html", {
        "title":"Viewing Customer", "customer":customer
        })

templates/customer-new.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Customers
{% endblock title %}

{% block content %}

    <section class="app-content">

      <div class="row">
        <div class="col-md-12 col-lg-12">
          <legend>Customer Information </legend>
          <form name="new-c" action="{% url "customer:customer-addnew" %}" class="form" method="post">
            {% csrf_token %}

            <span style="margin-left:0px;">Title</span> <select name="title" class="input-sm" {% if customer.title != None %}value="{{customer.title}}" {% endif %} style="margin-right:45px;" />
              <option value="Mr.">Mr.</option>
              <option value="Ms.">Ms.</option>
              <option value="Mrs.">Mrs.</option>
              <option value="Dr.">Dr.</option>
              <option value="S.">S.</option>
              <option value="Prof.">Prof.</option>
            </select>
            Sex <select name="sex" class="input-sm" {% if customer.sex == "Male" %} value="M" {% else %} value="F" {% endif %} style="margin-right:35px;">
              <option value="Male">M</option>
              <option value="Female">F</option>
            </select>
            <hr />
            First Name <input class="input-sm" name="fname" type="text" {% if customer.first_name != None %} value="{{customer.first_name}}" {% endif %} placeholder="First Name" size="25" />
            Middle Name <input class="input-sm" name="mname" type="text" {% if customer.middle_name != None %} value="{{customer.middle_name}}" {% endif %} placeholder="Middle Name" size="25" />
            Last Name <input class="input-sm" name="lname" type="text" {% if customer.last_name != None %} value="{{customer.last_name}}" {% endif %} placeholder="Last Name" size="30" /> <hr />
            Mobile 1 <input class="input-sm" name="mobile1" type="text" {% if customer.mobile1 != None %} value="{{customer.mobile1}}" {% endif %} placeholder="Mobile 1" size="25" />
            Mobile 2 <input class="input-sm" name="mobile2" type="text" {% if customer.mobile2 != None %} value="{{customer.mobile2}}" {% endif %} placeholder="Mobile 2" size="25" />
            Office Phone <input class="input-sm" name="ophone" type="text" {% if customer.office_phone != None %} value="{{customer.office_phone}}" {% endif %} placeholder="Office Phone" size="25" />
            Residence Phone <input class="input-sm" name="rphone" type="text" {% if customer.residence_phone != None %} value="{{customer.residence_phone}}" {% endif %} placeholder="Residence Phone" size="25" /><br /><hr />
            Email <input type="text" class="input-sm" name="email" {% if customer.email != None %} value="{{customer.email}}" {% endif %} placeholder="Email" size="45" />
            Birthday Date <input class="input-sm" name="bod" type="text" {% if customer.date_of_birth != None %} value="{{customer.date_of_birth}}" {% endif %} placeholder="Birthday Date" size="30" />
            Anniversary Date <input class="input-sm" name="ann-date" type="text" {% if customer.anniversary != None %} value="{{customer.anniversary}}" {% endif %} placeholder="Anniversary Date" size="30" /><hr />

            Special Remarks <input type="text" class="input-sm" name="specialRemarks" {% if customer.comments != None %} value="{{customer.comments}}" {% endif %} placeholder = "Special Remarks" size="150" /><hr />

            <legend> Addresses </legend>
            <h5>Residence Address</h5>
            Address Line 1 <input class="input-sm" name="add1" type="text" {% if customer.addline1 != None %} value="{{customer.addline1}}" {% endif %} placeholder="Address Line 1" size="30" />
            Address Line 1 <input class="input-sm" name="add2" type="text" {% if customer.addline2 != None %} value="{{customer.addline2}}" {% endif %} placeholder="Address Line 2" size="30" />
            Locality <input type="text" name="locality" class="input-sm" {% if customer.locality != None %} value="{{customer.locality}}" {% endif %} placeholder="Locality" size="15" />
            Pin Code <input type="text" name="pincode" class="input-sm" {% if customer.pincode != None %} value="{{customer.pincode}}" {% endif %} placeholder="Pin Code" size="15" />

            <h5>Office Address</h5>
            Address Line 1 <input class="input-sm" name="add1" type="text" {% if customer.addline1 != None %} value="{{customer.addline1}}" {% endif %} placeholder="Address Line 1" size="30" />
            Address Line 1 <input class="input-sm" name="add2" type="text" {% if customer.addline2 != None %} value="{{customer.addline2}}" {% endif %} placeholder="Address Line 2" size="30" />
            Locality <input type="text" name="locality" class="input-sm" {% if customer.locality != None %} value="{{customer.locality}}" {% endif %} placeholder="Locality" size="15" />
            Pin Code <input type="text" name="pincode" class="input-sm" {% if customer.pincode != None %} value="{{customer.pincode}}" {% endif %} placeholder="Pin Code" size="15" />
            <br /><br />

            <button type="submit" name="save-form" class="btn btn-success">Save</button>

          </form>
        </div>

      </div>

      <hr />
      <hr />

      <!-- <div class="row">
        <div class="col-md-12">
          <table id="customer" class="table table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Sex</th>
                <th>Locality</th>
                <th>Email</th>
                <th>Mobile Number</th>
                <th>Landline Number</th>
                <th>Date of Birth</th>
              </tr>
            </thead>
            <tbody>
              {% for each in customers %}
              <tr>
                <td>{{each.id}}</td>
                <td>{{each.title}}</td>
                <td><a href="{% url "customer:customer-view" each.pk %}">{{each.first_name}}</a></td>
                <td>{{each.last_name}}</td>
                <td>{{each.sex}}</td>
                <td>{{each.locality}}</td>
                <td>{{each.email}}</td>
                <td>{{each.mobile1}}</td>
                <td>{{each.residence_phone}}</td>
                <td>{{each.date_of_birth}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div> -->

    </section>

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Dashboard
{% endblock title %}

{% block content %}

      <section class="app-content">
          <div class="row">
              <div class="col-md-6 col-sm-6">
                  <div class="widget p-md clearfix">
                      <div class="pull-left">
                          <h3 class="widget-title">Welcome to Infinity</h3><small class="text-color">Number of views</small></div><span class="pull-right fz-lg fw-500 counter" data-plugin="counterUp">102</span></div>
              </div>
              <div class="col-md-6 col-sm-6">
                  <div class="widget p-md clearfix">
                      <div class="pull-left">
                          <h3 class="widget-title">Active</h3><small class="text-color">Loads / contact</small></div><span class="pull-right fz-lg fw-500 counter" data-plugin="counterUp">325</span></div>
              </div>
          </div>
          <div class="row">
              <div class="col-md-3 col-sm-6">
                  <div class="widget stats-widget">
                      <div class="widget-body clearfix">
                          <div class="pull-left">
                              <h3 class="widget-title text-primary"><span class="counter" data-plugin="counterUp">66.136</span>k</h3><small class="text-color">Total customers</small></div><span class="pull-right big-icon watermark"><i class="fa fa-paperclip"></i></span></div>
                  </div>
              </div>
              <div class="col-md-3 col-sm-6">
                  <div class="widget stats-widget">
                      <div class="widget-body clearfix">
                          <div class="pull-left">
                              <h3 class="widget-title text-danger"><span class="counter" data-plugin="counterUp">3.490</span>k</h3><small class="text-color">Total Pending Orders</small></div><span class="pull-right big-icon watermark"><i class="fa fa-ban"></i></span></div>
                  </div>
              </div>
              <div class="col-md-3 col-sm-6">
                  <div class=d"widget stats-widget">
                      <div class="widget-body clearfix">
                          <div class="pull-left">
                              <h3 class="widget-title text-success"><span class="counter" data-plugin="counterUp">8.378</span>k</h3><small class="text-color">Today's Birthdays</small></div><span class="pull-right big-icon watermark"><i class="fa fa-unlock-alt"></i></span></div>
                  </div>
              </div>
              <div class="col-md-3 col-sm-6">
                  <div class="widget stats-widget">
                      <div class="widget-body clearfix">
                          <div class="pull-left">
                              <h3 class="widget-title text-warning"><span class="counter" data-plugin="counterUp">3.490</span>k</h3><small class="text-color">Today's Followups</small></div><span class="pull-right big-icon watermark"><i class="fa fa-file-text-o"></i></span></div>
                  </div>
              </div>
          </div>

      </section>

{% endblock content %}

templates/orders-new.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Customers
{% endblock title %}

{% block content %}

    <section class="app-content">

      <div class="row">
        <div class="col-md-12 col-lg-12">
          <legend>Select Customer </legend>
          <form name="new-c" action="{% url "orders:index" %}" class="form" method="post">
            {% csrf_token %}
            <select name="customerpk" style="width:450px; height:35px;">
              {% for each in customer %}
                <option value="{{each.pk}}">{{each.name}}</option>
              {% endfor %}
            </select>

            <hr />

            <legend> Shipping Address </legend>
            Address Line 1 <input class="input-sm" name="add1" type="text" {% if customer.addline1 != None %} value="{{customer.addline1}}" {% endif %} placeholder="Address Line 1" size="30" />
            Address Line 1 <input class="input-sm" name="add2" type="text" {% if customer.addline2 != None %} value="{{customer.addline2}}" {% endif %} placeholder="Address Line 2" size="30" />
            Locality <input type="text" name="locality" class="input-sm" {% if customer.locality != None %} value="{{customer.locality}}" {% endif %} placeholder="Locality" size="15" />
            Pin Code <input type="text" name="pincode" class="input-sm" {% if customer.pincode != None %} value="{{customer.pincode}}" {% endif %} placeholder="Pin Code" size="15" />

            <hr />

            <legend> Order Details </legend>

            <br /><button type="submit" name="save-form" class="btn btn-success">Save</button>

          </form>
        </div>

      </div>

      <hr />
      <hr />

      <!-- <div class="row">
        <div class="col-md-12">
          <table id="customer" class="table table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Sex</th>
                <th>Locality</th>
                <th>Email</th>
                <th>Mobile Number</th>
                <th>Landline Number</th>
                <th>Date of Birth</th>
              </tr>
            </thead>
            <tbody>
              {% for each in customers %}
              <tr>
                <td>{{each.id}}</td>
                <td>{{each.title}}</td>
                <td><a href="{% url "customer:customer-view" each.pk %}">{{each.first_name}}</a></td>
                <td>{{each.last_name}}</td>
                <td>{{each.sex}}</td>
                <td>{{each.locality}}</td>
                <td>{{each.email}}</td>
                <td>{{each.mobile1}}</td>
                <td>{{each.residence_phone}}</td>
                <td>{{each.date_of_birth}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div> -->

    </section>

{% endblock content %}

templates/signup.html
<!DOCTYPE html><html lang="en">
<!-- Mirrored from envato.rathemes.com/infinity/topbar/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 01 Jun 2016 13:16:40 GMT -->
<head><meta charset="UTF-8"><title>Infinity - Bootstrap Admin Template</title><meta name="description" content="Admin, Dashboard, Bootstrap"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="shortcut icon" sizes="196x196" href="../assets/images/logo.png"><link rel="stylesheet" href="../libs/bower/font-awesome/css/font-awesome.min.css"><link rel="stylesheet" href="../libs/bower/material-design-iconic-font/dist/css/material-design-iconic-font.min.css"><link rel="stylesheet" href="../libs/bower/animate.css/animate.min.css"><link rel="stylesheet" href="../assets/css/bootstrap.css"><link rel="stylesheet" href="../assets/css/app.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900,300"></head><body class="simple-page"><div id="back-to-home"><a href="index.html" class="btn btn-outline btn-default"><i class="fa fa-home animated zoomIn"></i></a></div><div class="simple-page-wrap"><div class="simple-page-logo animated swing"><a href="index.html"><span><i class="fa fa-gg"></i></span> <span>Infinity</span></a></div><div class="simple-page-form animated flipInY" id="signup-form"><h4 class="form-title m-b-xl text-center">Sign Up For a new Account</h4><form action="#"><div class="form-group"><input id="sign-up-name" type="text" class="form-control" placeholder="Name"></div><div class="form-group"><input id="sign-up-email" type="email" class="form-control" placeholder="Email"></div><div class="form-group"><input id="sign-up-password" type="password" class="form-control" placeholder="Password"></div><div class="form-group m-b-xl"><div class="checkbox checkbox-primary"><input type="checkbox" id="keep_me_logged_in"><label for="keep_me_logged_in">Keep me signed in</label></div></div><input type="submit" class="btn btn-primary" value="SING IN"></form></div><div class="simple-page-footer"><p><small>Do you have an account ?</small> <a href="login.html">SIGN IN</a></p></div></div></body>
<!-- Mirrored from envato.rathemes.com/infinity/topbar/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 01 Jun 2016 13:16:40 GMT -->
</html>